gitlab-ce:
  restart: always
  image: 'gitlab/gitlab-ce:9.1.0-ce.0'
  hostname: 'dev.incept.infypedia.org'
  links:
    - postgresql:postgresql
    - redis:redis
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      postgresql['enable'] = false
      gitlab_rails['time_zone'] = 'Asia/Kolkata'
      gitlab_rails['db_username'] = "gitlab"
      gitlab_rails['db_password'] = "gitlab"
      gitlab_rails['db_host'] = "postgresql"
      gitlab_rails['db_port'] = "5432"
      gitlab_rails['db_database'] = "gitlabhq_production"
      gitlab_rails['db_adapter'] = 'postgresql'
      gitlab_rails['db_encoding'] = 'utf8'
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = "smtp.gmail.com"
      gitlab_rails['smtp_port'] = 587
      gitlab_rails['smtp_domain'] = "smtp.gmail.com" 
      gitlab_rails['smtp_user_name'] = "jenkins-travel@infibeam.net"
      gitlab_rails['smtp_password'] = "infibeam"
      gitlab_rails['smtp_authentication'] = "login"
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_tls'] = false
      gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
      gitlab_rails['gitlab_email_from'] = 'jenkins-travel@infibeam.net'
      gitlab_rails['gitlab_email_reply_to'] = 'jenkins-travel@infibeam.net'
      redis['enable'] = false
      gitlab_rails['redis_host'] = 'redis'
      gitlab_rails['redis_port'] = '6379'
      external_url 'https://dev.incept.infypedia.org'
      nginx['enable'] = true
      nginx['redirect_http_to_https'] = true
      nginx['ssl_certificate'] = "/etc/gitlab/ssl/fullchain.pem"
      nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/privkey.pem"      
      gitlab_rails['registry_enabled'] = true
      registry_external_url 'https://dev.incept.infypedia.org:4567'
      registry_nginx['ssl_certificate'] = "/etc/gitlab/ssl/fullchain.pem"
      registry_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/privkey.pem"      
      registry_nginx['listen_port'] = 4567
      gitlab_rails['gitlab_shell_ssh_port'] = 30022
  ports:
    - "443:443"
    - "30022:22"
    - "4567:4567"
  volumes:
    - /opt/infibeam/docker-volumes/gitlab-ce/config:/etc/gitlab:rw
    - /opt/infibeam/docker-volumes/gitlab-ce/logs:/var/log/gitlab:rw
    - /opt/infibeam/docker-volumes/gitlab-ce/data:/var/opt/gitlab:rw

postgresql:
  restart: always
  image: postgres:9.6.2-alpine
  environment:
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=gitlab
    - POSTGRES_DB=gitlabhq_production
  ports:
    - "5432:5432"
  volumes:
    - /opt/infibeam/docker-volumes/gitlab-ce/postgresql:/var/lib/postgresql:rw

redis:
  restart: always
  image: redis:3.0.7-alpine 
