postgresql:
  restart: always
  image: postgres:9.6.2-alpine
  environment:
    - POSTGRES_USER=prashant
    - POSTGRES_PASSWORD=prashant
    - POSTGRES_DB=testdb
  ports:
    - "5432:5432"
  volumes:
    - /data/docker-volumes/postgresql:/var/lib/postgresql:rw
